### ISSUE TITLE
画面に表示される操作要素は音声による対話が終了すると共に表示されなくなる必要があります。スキルとのインタラクションが終了したあとにインタラクティブ要素が選択されるとナビゲーションの問題が発生する可能があります。 

### ISSUE THREAD

**Issue by EngineerLabShimazu** [GenkiShimazu/skill-vpythonista-cactus#15]
> 4.    画面に表示される操作要素は音声による対話が終了すると共に表示されなくなる必要があります。スキルとのインタラクションが終了したあとにインタラクティブ要素が選択されるとナビゲーションの問題が発生する可能があります。 
> 
> 再現手順1： 
> ユーザー：アレクサ、すくすくさぼてんを開いて 
> スキル　：はい、きみのサボテンはこちらです。全長は0ミリメートルです。さぼてんに水をあげますか？ 
> ユーザー：ストップ 
> スキル　：Goodbye! 
> （スキルの画面が30秒ほど継続して表示） 
> 
> 再現手順2： 
> ユーザー：アレクサ、すくすくさぼてんを開いて 
> スキル　：はい、きみのサボテンはこちらです。全長は0ミリメートルです。さぼてんに水をあげますか？ 
> ユーザー：キャンセル 
> スキル　：Goodbye! 
> （スキルの画面が30秒ほど継続して表示） 
> 
> 画面表示および操作については、[申請チェックリスト](https://developer.amazon.com/ja/docs/custom-skills/functional-testing-for-a-custom-skill.html?ref_=pe_679090_102923190#cert-screen-display) 参照してください。

**Comment by EngineerLabShimazu** [comment]
`CancelOrStopIntentHandler` にこれ必要らしい

js
```javascript
withShouldEndSession
```

py
```python
set_should_end_session
```

**Comment by GenkiShimazu** [comment]
[このメッセージ](https://vpythonista.slack.com/archives/CKT401TDW/p1562845220002200)で[いただいた関数](https://github.com/alexa/skill-sample-python-quiz-game/blob/4858645722fa4c228247473db1f07f0a3994d93f/lambda/py/alexa/util.py#L40-L51)　でいけました！
